name: project-name
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - pip:
    - ipykernel
    - ipywidgets
    - matplotlib
    - numpy
    - pandas
    - pre-commit
    - scipy
    - seaborn
    - scikit-learn
    - tqdm
    - watermark
